### ISSUE TITLE
Data not converging

### ISSUE THREAD

**Issue by DavidCao1993** [hugoycj/2.5d-gaussian-splatting#7]
the same dataset I run gaussian-splatting, it converged. but 2dgs not.  should i adjust some param or something?
i train 2dgs without mask. the dataset is large area pictures captured by unmanned aerial vehicle and using colmap to calculate the pose.
![20240426142006](https://github.com/hugoycj/2dgs-gaustudio/assets/24777577/2761b2e4-c7e7-4dad-89ad-dd007cf9e977)

**Comment by hugoycj** [comment]
@DavidCao1993 Hi David, we've just released a new implementation of the distortion loss function. Would you mind trying it again and see if the results are better?

**Comment by DavidCao1993** [comment]
@hugoycj Hi hugoycj, i update the code but another problem happend.
![image](https://github.com/hugoycj/2.5d-gaussian-splatting/assets/24777577/9f32e313-068e-4fb9-a924-8338fe986532)
The dataset i trainning without mask. you may not have considered this situation.

**Comment by hugoycj** [comment]
We have updated the rasterizer for improved distortion loss. You need to reinstall the latest version gaustudio rasterizer

**Comment by hugoycj** [comment]
Sorry to bother! I forget to push the latest version. The current latest version with median_weight cache is availabe
<img width="1434" alt="image" src="https://github.com/hugoycj/2.5d-gaussian-splatting/assets/40767265/d862187a-b1fe-4f45-b3bd-e668bd28c496">
